ImobilidadeFinal/Models/Negocio.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImobilidadeFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Negocio
    {
        public string Valor { get; set; }
        public int IdImovel { get; set; }
        public int IdTipoNegocio { get; set; }
    
        public virtual Imovel Imovel { get; set; }
        public virtual TipoNegocio TipoNegocio { get; set; }
    }
}

ImobilidadeFinal/Controllers/NegocioController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ImobilidadeFinal.Models;

namespace ImobilidadeFinal.Controllers
{
    public class NegocioController : BaseController
    {
        private ImovelBDEntities db = new ImovelBDEntities();

        public ActionResult Index()
        {
            var negocios = db.Negocio.Include("Imovel").Include("TipoNegocio").ToList();
            return View(negocios);
        }

        public ActionResult Inserir()
        {
            ViewBag.IdImovel = new SelectList(db.Imovel, "IdImovel", "IdImovel");
            ViewBag.IdTipoNegocio = new SelectList(db.TipoNegocio, "IdTipoNegocio", "NomeTipoNegocio");
            return View();
        }

        [HttpPost]
        public ActionResult Inserir(Negocio negocio)
        {
            if (ModelState.IsValid)
            {
                db.Negocio.Add(negocio);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.IdImovel = new SelectList(db.Imovel, "IdImovel", "IdImovel");
            ViewBag.IdTipoNegocio = new SelectList(db.TipoNegocio, "IdTipoNegocio", "NomeTipoNegocio");
            return View(negocio);
        }

        public ActionResult Alterar(int? id, int? id2)
        {
            if (id == null && id2 == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Negocio negocio = db.Negocio.Find(id, id2);
            if (negocio == null)
            {
                return HttpNotFound();
            }
            ViewBag.IdImovel = new SelectList(db.Imovel, "IdImovel", "IdImovel", negocio.IdImovel);
            ViewBag.IdTipoNegocio = new SelectList(db.TipoNegocio, "IdTipoNegocio", "NomeTipoNegocio", negocio.IdTipoNegocio);
            return View(negocio);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Alterar([Bind(Include = "IdNegocio,NomeNegocio,IdImovel,IdTipoNegocio")] Negocio negocio)
        {
            if (ModelState.IsValid)
            {
                db.Entry(negocio).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.IdImovel = new SelectList(db.Imovel, "IdImovel", "IdImovel", negocio.IdImovel);
            ViewBag.IdTipoNegocio = new SelectList(db.TipoNegocio, "IdTipoNegocio", "NomeTipoNegocio", negocio.IdTipoNegocio);
            return View(negocio);
        }

        public ActionResult Excluir(int? id, int? id2)
        {
            if (id == null && id2 == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Negocio negocio = db.Negocio.Find(id, id2);
            if (negocio == null)
            {
                return HttpNotFound();
            }
            return View(negocio);
        }

        [HttpPost, ActionName("Excluir")]
        [ValidateAntiForgeryToken]
        public ActionResult ErroExcluir(int id, int id2)
        {
            try
            {
                Negocio negocio = db.Negocio.Find(id, id2);
                db.Negocio.Remove(negocio);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                return RedirectToAction("ErroExcluir");
            }
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        
        

    }
}

ImobilidadeFinal/Views/Negocio/Alterar.cshtml
@model ImobilidadeFinal.Models.Negocio

@{
    ViewBag.Title = "Editar Negócio";
}

<h2>Editar Negócio</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Negocio</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @*@Html.HiddenFor(model => model.IdTipoNegocio)
            @Html.HiddenFor(model => model.IdImovel) *@

        <div class="form-group">
            @Html.LabelFor(model => model.Valor, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Valor, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Valor, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IdImovel, "IdImovel", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("IdImovel", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IdImovel, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IdTipoNegocio, "IdTipoNegocio", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("IdTipoNegocio", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IdTipoNegocio, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Salvar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Voltar", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

@{ Html.EnableClientValidation(); }
@{ Html.EnableUnobtrusiveJavaScript();}

ImobilidadeFinal/Views/Negocio/ErroExcluir.cshtml
@model ImobilidadeFinal.Models.Negocio

@{
    ViewBag.Title = "ErroExcluir";
}

<h4>Erro ao excluir negócio!</h4>

<div>
    @Html.ActionLink("Voltar", "Index")
</div>

ImobilidadeFinal/Views/Negocio/Excluir.cshtml
@model ImobilidadeFinal.Models.Negocio

@{
    ViewBag.Title = "Exclusão de Negócio";
}

<h2>Exclusão de Negócio</h2>

<h3>Você tem certeza que pretende excluir isso?</h3>
<div>
    <h4>Exclusão de Negócios</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Valor)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Valor)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Imovel.Vagas)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Imovel.Vagas)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TipoNegocio.NomeTipoNegocio)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TipoNegocio.NomeTipoNegocio)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Excluir" class="btn btn-default" /> |
            @Html.ActionLink("Voltar", "Index")
        </div>
    }
</div>

ImobilidadeFinal/Views/Negocio/Index.cshtml
@model IEnumerable<ImobilidadeFinal.Models.Negocio>

@{
    ViewBag.Title = "Negócios";
}

<h2>Negócios</h2>

<p>
    <table class="table">
        <tr>
            <th>
                @Html.DisplayName("Valor do Negócio")
            </th>
            <th>
                @Html.DisplayName("Código do Imóvel")
            </th>
            <th>
                @Html.DisplayName("Nome do Tipo de Negócio")
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Valor)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Imovel.IdImovel)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TipoNegocio.NomeTipoNegocio)
                </td>
                <td>
                    @Html.ActionLink("Alterar", "Alterar", new { id = item.IdImovel, id2 = item.IdTipoNegocio }) 
                    @Html.ActionLink("Excluir", "Excluir", new { id = item.IdImovel, id2 = item.IdTipoNegocio })
                </td>
            </tr>
        }

</p>

<h2>Criar Negócio</h2>

<p>
    @Html.ActionLink("Adicionar Negócio", "Inserir", "Negocio")
</p>

ImobilidadeFinal/Views/Negocio/Inserir.cshtml
@model ImobilidadeFinal.Models.Negocio

@{
    ViewBag.Title = "Criação de Negócio";
}

<h2>Criação de Negócio</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Criação de Negócio</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.Label("Valor do Negócio", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Valor, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Valor, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Nome do Imóvel", "Id do Imovel", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("IdImovel", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IdImovel, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Nome do Tipo de Negócio", "Tipo do Negó'cio", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("IdTipoNegocio", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IdTipoNegocio, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Criar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Voltar", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

@{ Html.EnableClientValidation(); }
@{ Html.EnableUnobtrusiveJavaScript();}