ImobilidadeFinal/Models/Bairro.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImobilidadeFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bairro
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bairro()
        {
            this.Imovel = new HashSet<Imovel>();
        }
    
        public int IdBairro { get; set; }
        public string NomeBairro { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Imovel> Imovel { get; set; }
    }
}

ImobilidadeFinal/Controllers/BairroController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;
using ImobilidadeFinal.Models;

namespace ImobilidadeFinal.Controllers
{
    [OutputCache(Location = OutputCacheLocation.None, NoStore = true)]
    public class BairroController : BaseController
    {
        private ImovelBDEntities db = new ImovelBDEntities();

        public ActionResult Index()
        {
            var bairros = db.Bairro.ToList();
            return View(bairros);
        }

        public ActionResult Inserir()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Inserir(Bairro bairro)
        {
            if (ModelState.IsValid)
            {
                db.Bairro.Add(bairro);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(bairro);
        }

        public ActionResult Alterar(int id)
        {
            Bairro bairro = db.Bairro.Find(id);
            return View(bairro);
        }

        [HttpPost]
        public ActionResult Alterar(Bairro bairro)
        {
            if (ModelState.IsValid)
            {
                db.Entry(bairro).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(bairro);
        }

        public ActionResult Excluir(int id)
        {
            Bairro bairro = db.Bairro.Find(id);
            return View(bairro);
        }

        [HttpPost, ActionName("Excluir")]
        public ActionResult EfetuarExclusao(int id)
        {
            try
            {
                Bairro bairro = db.Bairro.Find(id);
                db.Bairro.Remove(bairro);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                return RedirectToAction("ErroExcluir");
            }
        }
    }
}

ImobilidadeFinal/Views/Bairro/Alterar.cshtml
@model ImobilidadeFinal.Models.Bairro

@{
    ViewBag.Title = "Alterar Bairro";
}

<h2>Alterar Bairro</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Bairro</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.IdBairro)

        <div class="form-group">
            @Html.LabelFor(model => model.NomeBairro, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NomeBairro, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NomeBairro, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Salvar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Voltar", "Index", "Bairro")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

@{ Html.EnableClientValidation(); }
@{ Html.EnableUnobtrusiveJavaScript();}

ImobilidadeFinal/Views/Bairro/ErroExcluir.cshtml
@model ImobilidadeFinal.Models.Bairro

@{
    ViewBag.Title = "Erro na Exclusão";
}

<h4>Erro ao excluir bairro!</h4>

<div>
    @Html.ActionLink("Voltar", "Index")
</div>

ImobilidadeFinal/Views/Bairro/Excluir.cshtml
@model ImobilidadeFinal.Models.Bairro

@{
    ViewBag.Title = "Exclusão de Bairros";
}

<h2>Exclusão de Bairros</h2>

<h3>Você tem certeza que deseja excluir este item?</h3>
<div>
    <h4>Bairro</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.NomeBairro)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NomeBairro)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Deletar" class="btn btn-default" /> |
            @Html.ActionLink("Voltar", "Index")
        </div>
    }
</div>

ImobilidadeFinal/Views/Bairro/Index.cshtml
@model IEnumerable<ImobilidadeFinal.Models.Bairro>

@{
    ViewBag.Title = "Bairros";
}

<h2>Bairros</h2>

<p>
    @Html.ActionLink("Inserir Novo Bairro", "Inserir")
</p>


<table class="table">
    <tr>
        <th>
            @Html.DisplayName("ID do Bairro")
        </th>
        <th>
            @Html.DisplayName("Nome do Bairro")
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.IdBairro)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NomeBairro)
            </td>
            <td>
                @Html.ActionLink("Alterar", "Alterar", new { id = item.IdBairro }) |
                @Html.ActionLink("Excluir", "Excluir", new { id = item.IdBairro })
            </td>
        </tr>
    }

</table>

ImobilidadeFinal/Views/Bairro/Inserir.cshtml
@model ImobilidadeFinal.Models.Bairro

@{
    ViewBag.Title = "Criar Bairro";
}

<h2>Criar Bairro</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Bairro</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.Label("Nome do Bairro", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NomeBairro, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NomeBairro, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Criar" class="btn btn-default" />
            </div>
        </div>
    </div>
}



<div>
    @Html.ActionLink("Voltar", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}
@{ Html.EnableClientValidation(); }
@{ Html.EnableUnobtrusiveJavaScript();}