ImobilidadeFinal/Models/Imovel.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImobilidadeFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Imovel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Imovel()
        {
            this.Negocio = new HashSet<Negocio>();
        }
    
        public int IdImovel { get; set; }
        public string Vagas { get; set; }
        public string Quartos { get; set; }
        public string Suite { get; set; }
        public string Area { get; set; }
        public string ValorTotal { get; set; }
        public int IdProprietario { get; set; }
        public int IdBairro { get; set; }
        public int IdTipoImovel { get; set; }
    
        public virtual Bairro Bairro { get; set; }
        public virtual Proprietario Proprietario { get; set; }
        public virtual TipoImovel TipoImovel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Negocio> Negocio { get; set; }
    }
}

ImobilidadeFinal/Controllers/ImovelController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;
using ImobilidadeFinal.Models;

namespace ImobilidadeFinal.Controllers
{
    [OutputCache(Location = OutputCacheLocation.None, NoStore = true)]
    public class ImovelController : BaseController
    {
        private ImovelBDEntities db = new ImovelBDEntities();

        public ActionResult Index()
        {
            var imoveis = db.Imovel.Include("Bairro").Include("Proprietario").Include("TipoImovel").ToList();
            return View(imoveis);
        }

        public ActionResult Inserir()
        {
            ViewBag.IdBairro = new SelectList(db.Bairro, "IdBairro", "NomeBairro");
            ViewBag.IdProprietario = new SelectList(db.Proprietario, "IdProprietario", "NomeProprietario");
            ViewBag.IdTipoImovel = new SelectList(db.TipoImovel, "IdTipoImovel", "NomeTipoImovel");
            return View();
        }

        [HttpPost]
        public ActionResult Inserir(Imovel imovel)
        {
            if (ModelState.IsValid)
            {
                db.Imovel.Add(imovel);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.IdBairro = new SelectList(db.Bairro, "IdBairro", "NomeBairro");
            ViewBag.IdProprietario = new SelectList(db.Proprietario, "IdProprietario", "NomeProprietario");
            ViewBag.IdTipoImovel = new SelectList(db.TipoImovel, "IdTipoImovel", "NomeTipoImovel");
            return View(imovel);
        }

        public ActionResult Alterar(int id)
        {
            Imovel imovel = db.Imovel.Find(id);
            ViewBag.IdBairro = new SelectList(db.Bairro, "IdBairro", "NomeBairro");
            ViewBag.IdProprietario = new SelectList(db.Proprietario, "IdProprietario", "NomeProprietario");
            ViewBag.IdTipoImovel = new SelectList(db.TipoImovel, "IdTipoImovel", "NomeTipoImovel");
            return View(imovel);
        }

        [HttpPost]
        public ActionResult Alterar(Imovel imovel)
        {
            if (ModelState.IsValid)
            {
                db.Entry(imovel).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.IdBairro = new SelectList(db.Bairro, "IdBairro", "NomeBairro");
            ViewBag.IdProprietario = new SelectList(db.Proprietario, "IdProprietario", "NomeProprietario");
            ViewBag.IdTipoImovel = new SelectList(db.TipoImovel, "IdTipoImovel", "NomeTipoImovel");
            return View(imovel);
        }

        public ActionResult Excluir(int id)
        {
            Imovel imovel = db.Imovel.Find(id);
            ViewBag.IdBairro = new SelectList(db.Bairro, "IdBairro", "NomeBairro");
            ViewBag.IdProprietario = new SelectList(db.Proprietario, "IdProprietario", "NomeProprietario");
            ViewBag.IdTipoImovel = new SelectList(db.TipoImovel, "IdTipoImovel", "NomeTipoImovel");
            return View(imovel);
        }

        [HttpPost, ActionName("Excluir")]
        public ActionResult EfetuarExclusao(int id)
        {
            try
            {
                Imovel imovel = db.Imovel.Find(id);
                db.Imovel.Remove(imovel);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                return RedirectToAction("ErroExcluir");
            }
        }

    }
}

ImobilidadeFinal/Views/Imovel/Alterar.cshtml
@model ImobilidadeFinal.Models.Imovel

@{
    ViewBag.Title = "Alterar Imóvel";
}

<h2>Alterar</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Imovel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.IdImovel)

        <div class="form-group">
            @Html.LabelFor(model => model.Vagas, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Vagas, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Vagas, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Quartos, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Quartos, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Quartos, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Suite, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Suite, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Suite, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Area, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Area, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Area, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ValorTotal, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ValorTotal, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ValorTotal, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IdProprietario, "IdProprietario", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("IdProprietario", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IdProprietario, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IdBairro, "IdBairro", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("IdBairro", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IdBairro, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IdTipoImovel, "IdTipoImovel", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("IdTipoImovel", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IdTipoImovel, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Salvar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Voltar", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

@{ Html.EnableClientValidation(); }
@{ Html.EnableUnobtrusiveJavaScript();}

ImobilidadeFinal/Views/Imovel/ErroExcluir.cshtml
@model ImobilidadeFinal.Models.Imovel

@{
    ViewBag.Title = "Erro na Exclusão";
}

<h4>Erro ao excluir imóvel!</h4>

<div>
    @Html.ActionLink("Voltar", "Index")
</div>

ImobilidadeFinal/Views/Imovel/Excluir.cshtml
@model ImobilidadeFinal.Models.Imovel

@{
    ViewBag.Title = "Exclusão de Imóveis";
}

<h2>Exclusão de Imóveis</h2>

<h3>Você tem certeza que deseja excluir este item?</h3>
<div>
    <h4>Imovel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Vagas)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Vagas)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Quartos)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Quartos)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Suite)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Suite)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Area)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Area)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ValorTotal)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ValorTotal)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Bairro.NomeBairro)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Bairro.NomeBairro)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Proprietario.NomeProprietario)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Proprietario.NomeProprietario)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TipoImovel.NomeTipoImovel)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TipoImovel.NomeTipoImovel)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Excluir" class="btn btn-default" /> |
            @Html.ActionLink("Voltar", "Index")
        </div>
    }
</div>

ImobilidadeFinal/Views/Imovel/Index.cshtml
@model IEnumerable<ImobilidadeFinal.Models.Imovel>

@{
    ViewBag.Title = "Index";
}

<h2>Imóveis</h2>

<p>
    @Html.ActionLink("Cadastrar Novo Imovel", "Inserir")
</p>


<table class="table">
    <tr>
        <th>
            @Html.DisplayName("ID Imóvel")
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Vagas)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Quartos)
        </th>
        <th>
            @Html.DisplayName("Suíte")
        </th>
        <th>
            @Html.DisplayName("Área")
        </th>
        <th>
            @Html.DisplayName("Valor Total")
        </th>
        <th>
            @Html.DisplayName("Nome do Bairro")
        </th>
        <th>
            @Html.DisplayName("Nome do Proprietário")
        </th>
        <th>
            @Html.DisplayName("Nome do Tipo do Imóvel")
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.IdImovel)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Vagas)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Quartos)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Suite)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Area)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ValorTotal)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Bairro.NomeBairro)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Proprietario.NomeProprietario)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TipoImovel.NomeTipoImovel)
        </td>
        <td>
            @Html.ActionLink("Alterar", "Alterar", new { id = item.IdImovel }) |
            @Html.ActionLink("Excluir", "Excluir", new { id = item.IdImovel })
        </td>
    </tr>
    }

</table>

ImobilidadeFinal/Views/Imovel/Inserir.cshtml
@model ImobilidadeFinal.Models.Imovel

@{
    ViewBag.Title = "Inserir Imóvel";
}

<h2>Inserir Imóvel</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Imóvel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Vagas, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Vagas, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Vagas, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Quartos, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Quartos, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Quartos, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Suítes", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Suite, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Suite, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Área", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Area, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Area, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Valor Total", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ValorTotal, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ValorTotal, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("IdProprietario", "Nome do Proprietário", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("IdProprietario", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IdProprietario, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("IdBairro", "Nome do Bairro", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("IdBairro", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IdBairro, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("IdTipoImovel", "Nome do Tipo do Imóvel", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("IdTipoImovel", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IdTipoImovel, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Salvar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Voltar", "Index", "Imovel")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

@{ Html.EnableClientValidation(); }
@{ Html.EnableUnobtrusiveJavaScript();}